services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
      - "25576:25575"
    environment:
      # Performance Settings
      EULA: "TRUE"
      MEMORY: "4G"
      MAX_MEMORY: "16G"
      RCON_PASSWORD: "password"
  
      VERSION: "1.21.8"

      # Server Settings
      DUMP_SERVER_PROPERTIES: "true"
      OVERRIDE_SERVER_PROPERTIES: "false"

    restart: "no"
    volumes:
      - ./data:/data
