version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8880:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 1080:1080/udp # Socks5
      - 1080:1080/tcp # Socks5
      - 8191:8191/udp # Flaresolverr
      - 8191:8191/tcp # Flaresolverr
    environment:
      - VPN_SERVICE_PROVIDER=SERVICE_PROVIDER_HERE
      - TZ=America/New_York
      - HTTPPROXY=on
      - SHADOWSOCKS=on
      - UPDATER_PERIOD=24h
      - VPN_TYPE=openvpn
      - OPENVPN_USER=OVPN_USER_HERE
      - OPENVPN_PASSWORD=OVPN_PASSWORD_HERE
      - SERVER_CITIES=New York City
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - ./wg0.conf:/gluetun/wireguard/wg0.conf
    restart: unless-stopped

  gluetun-socks5:
    image: serjs/go-socks5-proxy
    container_name: gluetun-socks5
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    restart: unless-stopped
