version: '3'
services:
  checker:
    image: alpine:latest
    container_name: gitlab-checker
    volumes:
      - /mnt:/mnt:ro
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]
    healthcheck:
      test: ["CMD-SHELL", "[ -d /mnt/cryptdata ]"]
      interval: 1s
      timeout: 1s
      start_period: 0s
      retries: 2147483647
    stop_grace_period: 1s
    restart: unless-stopped

  gitlab:
    image: gitlab/gitlab-ee:<version>-ee.0
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'
    ports:
      - '8081:80'
      # - '443:443'
      # - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
  
  db:
    image: postgres:15
    container_name: gitlab-db
    depends_on:
      mount-checker:
        condition: service_healthy
    volumes:
      - ./db:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: on-failure