version: '3'
services:
  checker:
    image: alpine:latest
    container_name: gitlab-checker
    volumes:
      - /mnt:/mnt:ro
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]
    healthcheck:
      test: ["CMD-SHELL", "[ -d /mnt/cryptdata/encrypted ]"]
      interval: 1s
      timeout: 1s
      start_period: 0s
      retries: 2147483647
    stop_grace_period: 1s
    restart: unless-stopped

  # checker:
  #   image: postgres:15-alpine
  #   container_name: gitlab-checker
  #   entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -h host.docker.internal -p 5432"]
  #     interval: 5s
  #     timeout: 3s
  #     start_period: 0s
  #     retries: 2147483647
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   restart: unless-stopped

  gitlab:
    image: gitlab/gitlab-ce:17.0.3-ce.0
    container_name: gitlab
    depends_on:
      checker:
        condition: service_healthy
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://git.YOURDOMAIN.COM'
        nginx['listen_addresses'] = ['127.0.0.1', 'host.docker.internal']
        nginx['listen_port'] = 8081
        nginx['listen_https'] = false
    ports:
      - '8081:8081'
    volumes:
      - /mnt/cryptdata/encrypted/gitlab/config:/etc/gitlab
      - /mnt/cryptdata/encrypted/gitlab/logs:/var/log/gitlab
      - /mnt/cryptdata/encrypted/gitlab/data:/var/opt/gitlab
    shm_size: '256m'
    restart: "no"