version: '3'
services:
  checker:
    image: postgres:15-alpine
    container_name: gitlab-checker
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h host.docker.internal -p 5432"]
      interval: 5s
      timeout: 3s
      start_period: 0s
      retries: 2147483647
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  gitlab:
    image: gitlab/gitlab-ee:17.0.3-ce.0
    container_name: gitlab
    depends_on:
      checker:
        condition: service_healthy
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab.example.com'
    ports:
      - '8081:80'
      # - '443:443'
      # - '22:22'
    volumes:
      - ./config:/etc/gitlab
      - /mnt/cryptdata/encrypted/gitlab/logs:/var/log/gitlab
      - /mnt/cryptdata/encrypted/gitlab/data:/var/opt/gitlab
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: '256m'
    restart: no