version: '3'
services:
  apache:
    build: .
    container_name: apache-server
    ports:
    - '8080:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
    - ./logs:/var/log/apache2
    restart: unless-stopped
