version: "3"

services:
  checker:
    image: postgres:16-alpine
    container_name: postgres-checker
    volumes:
      - /mnt:/mnt:ro
    entrypoint: ["/bin/sh", "-c", "while :; do sleep 1; done"]
    healthcheck:
      test: ["CMD-SHELL", "[ -d /mnt/cryptdata/encrypted ]"]
      interval: 1s
      timeout: 1s
      start_period: 0s
      retries: 2147483647
    stop_grace_period: 1s
    restart: "no"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    depends_on:
      checker:
        condition: service_healthy
    ports:
      - 5432:5432
    volumes:
      - /mnt/cryptdata/encrypted/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    restart: "no"
