services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/html
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/etc/caddy/caddy.d
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped