version: '3.9'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    mac_address: d0:ca:ab:cd:ef:01
    # Uncomment if you want to use Pi-Hole for DHCP
    # cap_add:
    #   - NET_ADMIN
    ports:
      # - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      # Uncomment if you want to use Pi-Hole for DHCP
      # - 67:67/udp
      - 8001:80/tcp
      # - 22:22/tcp
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.1.5
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_=192.168.1.6;192.168.1.13
    volumes:
      - ./pihole/volume:/etc/pihole:rw
      - ./pihole/config/hosts:/etc/hosts:ro
      - ./pihole/config/resolv.conf:/etc/resolv.conf:ro
      - ./pihole/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - ./pihole/config/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
    networks:
      home:
        ipv4_address: 192.168.1.5
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      home:
        ipv4_address: 192.168.1.6
    restart: unless-stopped

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ovs_eth1
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.5/30
