services:
  macos:
    image: sickcodes/docker-osx:naked@sha256:c6e360b9ada6abc64c3ca14f4ee9ba92af7b73a49d8856a76cdf37d9cd305cc0
    container_name: docker-osx
    devices:
      - /dev/kvm
    ports:
      - "5900:5999"
      - "1234:1234"
      - "50922:10022"
    volumes:
      - ./mac_hdd_ng.img:/image
      - ./OpenCore.qcow2:/bootdisk
    environment:
      - AUDIO_DRIVER=none
      - IMAGE_PATH=/image
      - BOOTDISK=/bootdisk
      - EXTRA=-display none -vnc 0.0.0.0:99,password-secret=secvnc0 -object secret,id=secvnc0,data=PASSWORD
      - ADDITIONAL_PORTS=hostfwd=tcp::1234-:1234,
      - DISPLAY="${DISPLAY:-:0.0}"
      - MAC_ADDRESS=${MAC_ADDRESS}
      - CPU=Haswell-noTSX
      - CPUID_FLAGS=kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on
    stop_grace_period: 3s
    restart: "no"