services:
  redis:
    image: redis:8.0.3-alpine
    container_name: redis-theatrack
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--requirepass", "password"]
    restart: unless-stopped
