services:
  modded:
    image: itzg/minecraft-server:java17
    container_name: modded
    tty: true
    stdin_open: true
    ports:
      - "25568:25565"
      - "25578:25575"
    environment:
      # Performance Settings
      EULA: "true"
      MEMORY: "4G"
      MAX_MEMORY: "12G"
      RCON_PASSWORD: "password"

      # CURSEFORGE
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: ${CF_API_KEY}
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
      # Optional: select a specific version/file
      CF_FILENAME_MATCHER: "1.1.0"

      # MODRINTH
      # MOD_PLATFORM: MODRINTH
      # MODRINTH_MODPACK: https://modrinth.com/modpack/the-pixelmon-modpack/version/9.2.8

      # Server Settings
      DUMP_SERVER_PROPERTIES: "true"
      OVERRIDE_SERVER_PROPERTIES: "false"

    volumes:
      - ./data:/data
      - ./downloads:/downloads
    restart: "no"