name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2
    volumes:
      - ./library:/data
      - /etc/localtime:/etc/localtime:ro
      - /opt/images:/opt/mount:ro # external library
      - ./immich.json:/opt/immich.json:ro
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      IMMICH_CONFIG_FILE: /opt/immich.json
    ports:
      - "0.0.0.0:2283:2283"
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
    restart: no
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    healthcheck:
      test: redis-cli ping || exit 1
    restart: no

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    shm_size: 128mb
    restart: no
    healthcheck:
      disable: false
