services:
  pixelmon:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25567:25565"
      - "25577:25575"
    environment:
      EULA: "TRUE"
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: https://www.modrinth.com/modpack/the-pixelmon-modpack
      MODRINTH_VERSION: 9.2.8
    volumes:
      - ./data:/data
    restart: unless-stopped